# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InventoryManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InventoryManager
  pod 'BarcodeScanner'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Functions'

  target 'InventoryManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
