name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # Job name is Test
    name: Build
    # This job runs on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
        xcode: ['/Applications/Xcode.app/Contents/Developer']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app/Contents/Developer
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

#     - name: Install Dependences
#       working-directory: ./iOS\ App
#       run: pod install
#       shell: bash
          
    - name: Build and test
#       working-directory: ./iOS\ App
      run: |
        cd iOS/ App
        xcodebuild clean test -project InventoryManager.xcodeproj -scheme InventoryManager -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env:
        destination: ${{ matrix.destination }}
      
    - name: Build
      working-directory: ./iOS\ App
      run: swift build -v
    - name: Run tests
      run: swift test -v
