name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # Job name is Test
    name: Build
    # This job runs on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8']
        xcode: ['/Applications/Xcode.app/Contents/Developer']

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Bundle Install
      working-directory: ./iOS\ App
      run: bundle install
      
    - name: Dependencies
      working-directory: ./iOS\ App
      run: bundle exec pod install
      env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
          
    - name: Build and test
      working-directory: ./iOS\ App
      run: bundle exec fastlane scan --destination "${destination}" --scheme "InventoryManager"
      env:
        destination: ${{ matrix.destination }}
        DEVELOPER_DIR: ${{ matrix.xcode }}
      
    - name: Build
      working-directory: ./iOS\ App
      run: swift build -v
    - name: Run tests
      run: swift test -v
